# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-Local-Extended
version:      0.50
version_from: lib/Time/Local/Extended.pm
installdirs:  site
requires:
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
